site_name: アプリにゃんこ大戦争
site_url: https://battlecats-server.f5.si/

theme:
  name: 'material'
  language: ja
  features:
    - navigation.tabs
    - navigation.top
  logo: https://cdn.discordapp.com/icons/755774191613247568/a07e5e6e7edf52a924c29849eefa0809.webp?size=512
  favicon: https://cdn.discordapp.com/icons/755774191613247568/a07e5e6e7edf52a924c29849eefa0809.webp
  palette:
    primary: orange
    accent: amber

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav:
  - ホーム: index.md
  - Botの使い方解説: bots.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/kvfjq7c
      name: Discordサーバー
